"""empty message

Revision ID: 8e606e5440e6
Revises: f7b61f7f6c6b
Create Date: 2020-10-24 22:52:16.635236

"""
from alembic import op
import sqlalchemy as sa
import app.utils.db
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e606e5440e6'
down_revision = 'f7b61f7f6c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('password', sa.String(length=128), nullable=False))
    op.add_column('user', sa.Column('start_of_day', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('timezone', sa.String(length=64), nullable=False))
    op.drop_index('email', table_name='user')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', mysql.VARCHAR(length=120), nullable=False))
    op.create_index('email', 'user', ['email'], unique=True)
    op.drop_column('user', 'timezone')
    op.drop_column('user', 'start_of_day')
    op.drop_column('user', 'password')
    op.drop_column('user', 'last_login')
    op.drop_column('user', 'created_on')
    # ### end Alembic commands ###
