"""empty message

Revision ID: b073624bfc7e
Revises: 8e606e5440e6
Create Date: 2020-10-25 00:02:24.527698

"""
from alembic import op
import sqlalchemy as sa
import app.utils.db
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b073624bfc7e'
down_revision = '8e606e5440e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'timezone')
    op.drop_column('user', 'start_of_day')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('start_of_day', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('timezone', mysql.VARCHAR(length=64), nullable=False))
    # ### end Alembic commands ###
